config/routes.rb
# generate url and connect url and path with code

Rails.application.routes.draw do
    devise_for :users
    root "posts#index"
    get "posts/profile/:id", to: "posts#profile", as: :post_profile
    get "users/profile/:id", to: "users#profile", as: :user_profile
    get 'users', to: 'users#index'
    resources :posts do
       resources :likes, only: [:create, :destroy]
       resources :comments
    end
  
    resources :users, only: [:index,:create,:show, :edit, :update]
    resources :posts, only: [:new, :create,:update,:show,:destroy] 
    resources :users, path: '/', only: %i[show] do
      post :follow, to: 'follows#create', as: :follow
      delete :follow, to: 'follows#destroy', as: :unfollow
    end
end

















# post :follow, to: 'follows#create    '
# delete :follow, to: 'follows#destroy  '
# post :follow, to: 'follows#create', as: :follow
# delete :follow, to: 'follows#destroy', as: :unfollow
# resources :homes
# post 'follow', to: 'counts#increment', as: 'follow'
# post 'unfollow', to: 'counts#decrement', as: 'unfollow'
# root "posts"

# resources :likes, only: [:create, :destroy], shallow: true
# resources :comments, only: [:index, :create, :destroy], shallow: true
# end
# resources :posts do
#   member do
#     post 'like'
#     post 'comment'
#   end
# end
# resources :users, only: [:edit, :update]
# get '/profile', to: 'posts#profile', as: 'profile'

  # get '/messages', to: 'messages#index', as: 'messages'
  # get "/profile/:user_name" => "posts#profile",as: :profile
  # resources :posts, path: '/', param: :user_name, only: %i[show] do
  #   post :follow, to: 'posts/follows#create', as: :follow
  #   delete :follow, to: 'posts/follows#destroy', as: :unfollow
  
  # get 'search', to: 'posts#search', as: 'search_posts'
  
  
  # resources :posts do
  #   collection do
  #     get :search
  #   end
  # end





  # post "posts/p_form", to: "posts#p_form"
  # resources :users, only: [:show]

  # root to: "devise/sessions#new"

  # devise_for :models
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/user.rb
class User < ApplicationRecord 
  include Followable
  
    validates :image, presence: false
  
    devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
         
    has_many :posts, dependent: :destroy

    has_many :likes,dependent: :destroy

    has_many :comments,dependent: :destroy
    
    has_one_attached :image
    
    
  end
  
  
  
  
  
  
  
  
  

  

  

  



  
  
  
  
  # has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  # has_many :followees, through: :followed_users
  # has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  # has_many :followers, through: :following_users
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_many :likes
  # has_many :comments
  # validates :username, presence: true, uniqueness:{case_sensitive: false}      
  
        #  def change
        #   add_column :users, :followers_count, :integer, null: false, default: 0
        #   add_column :users, :followings_count, :integer, null: false, default: 0
        # end
        
        #  attr_writer :login
        #  def login
        #    @login || self.username|| self.email
        #  end
        
        #   def self.find_first_by_auth_conditions(warden_conditions)
        #     conditions = warden_conditions.dup
        #     if(login=conditions.delete(:login))
        #       where(conditions).where(["lower(username)=:value or lower(email)=:value",{:value=> login.downcase}]).first
        #     else
        #       if conditions[:username].nil?
        #         where(conditions).first
        #       else
        #         where(username: conditions[:username]).first
        #       end
        #     end
        #   end
        
        

        
        


        

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users=User.where.not(id: current_user.id)
    end
   
    def show
        # @user----------instance object----------specific
        @user = User.find(params[:id])
        @posts = @user.posts.order(created_at: :desc)
        @followers = current_user.followers
        @followings = current_user.followings    
    end

    def edit 
        @user = User.find(params[:id])
        @posts = current_user.posts
    end

    def profile
        @user = User.find(params[:id])
        @posts = current_user.posts
        @followers = @user.followers
        @followings = @user.followings
        
        if current_user.id == @user.id
          redirect_to user_path(current_user)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params) # strong params
          redirect_to user_path(@user), notice: 'Profile updated successfully.'
        else
          render :edit
        end
    end

    private
  
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :image)
    end

end

   
    




    # def follow
    #   @user = User.find(params[:id])
    #   @post_ids = @user.post_ids
    #   current_user.followees << @user
    #   redirect_back(fallback_location: user_path(@user))
    # end
    
    # def unfollow
    #   @user = User.find(params[:id])
    #   current_user.followed_users.find_by(followee_id: @user.id).destroy
    #   redirect_back(fallback_location: user_path(@user))
    # end
    

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<style>
  .container{
      border:2px solid black;
      height:380px;
      width:600px;
      border-radius:50px;
      padding-top:20px;
      text-align:center;
  }
  h5{
      padding-top:50px;
      padding-bottom:30px;
  }
</style>
 
<div class="container">
  <%= form_for current_user, url: user_path(current_user), method: :put do |f| %>
      <h6> <%= f.label :Image %><br>
      <%= f.file_field :image, class: "form-control" %></h6>
      <h5> <%= f.label :UserName %><br>
      <%= f.text_field :username,placeholder:"          ----username----", autofocus: true %></h5>
      <h5><%= f.submit "Submit", class: "btn btn-primary" %>        <%= link_to "Back", root_path,class: "btn btn-primary" %></h5>
  <% end %>
</div>

app/views/users/index.html.erb
<style>
  table{
      border:1px solid black;
      text-align: center;
      width:69% !important;
  }
  th{
      border:1px solid black;
  }
  td{
      border: 1px solid black;
  }
  .center {
      margin-left: auto;
      margin-right: auto;
  }
  .unfollow-button{
      background-color:#f55242;
      border-radius:14px;
  }
  .follow-button{
      background-color:#73ec73;
      border-radius:14px;
  }
  .unfollow-button:hover,.follow-button:hover{
      box-shadow:1px 1px 1px 1px black;
      border-radius:18px;
  }
  #example_wrapper .row{
      width: 100%;
  }
  #example_filter{
      text-align:end;
  }
  .dataTables_length{
      margin-left:10px;
  }
</style>

<table class="table table-striped center" id="example">
  <thead >
    <tr>
      <th><h4>User</h4> </th>
      <th><h4>Action</h4> </th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |f| %>
      <tr>
        <td><h5><%= link_to f.username, user_profile_path(f.id) %></h5></td>
        <td>
          <% if current_user.is_following?(f) %>
            <%= button_to user_unfollow_path(f), class: "unfollow-button", method: :delete do %>
              Unfollow
            <% end %>
          <% else %>
            <%= button_to user_follow_path(f), class: "follow-button", method: :post do %>
              Follow
            <% end %>
          <% end %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

<script>
$(document).ready( function () {
new DataTable('#example');
});
</script>

app/views/users/profile.html.erb
<style>
  .profile{
      width:  191px;
      height: 183px;
      border-radius: 50%;
      box-shadow: 2px 2px 2px black;
      margin-bottom: 22px;
      border: 2px solid black;
  }
  .container{
      text-align:center;
  }
  table{
      border:1px solid black;
      text-align: center;
      width:40px;
      height:145px;
      margin-left:8px;
  }
  th{
      border:1px solid black;
      box-shadow: 1px 1px 1px black;
  }
  td{
      border: 1px solid black;
      box-shadow: 1px 1px 1px black;
  }
  .col-8{
      margin-left:454px;
      padding-right: 99px;
  }
  .photo{
      margin-top:60px;
      height: 367px;
      width: 347px;
      padding-bottom: 32px;
      border:1px solid black;
      border:10px solid transparent;
      box-shadow:2px 2px 5px black;
      margin-left:100px;
  }
  P{
      position:relative;
      bottom:26px;
      left:10px;
      margin-left:100px;
      font-family: 'Dancing Script', cursive;
  }
  .col-4{
      border-right: 1px solid black;
      position:fixed;
      font-family: 'Dancing Script', cursive;
  }
  .like-section{
      position: absolute;
      bottom: 33px;
      padding-bottom:10px;
      right: 105px;
  }
  .like-button{
      background-color: #3897f0;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
      margin-left:30px;
  }
  .like-button:hover{
      background-color: #3173c0;
  }
  .unlike-button{
      background-color: #ed4956;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
      margin-left:30px;
  }
  .unlike-button:hover{
      background-color: #c81826;
  }
  .like-count{
      font-weight: bold;
      padding-left:10px;
  }
  .dropdown{
      position: absolute;
      bottom: 10px;
      left: 59px;
  }
  .row{
      width:100%;
  }
  .close{
      margin:0px!important;
      cursor: auto!important;
  }
  .column{
      margin-left:129px!important;
  }
  .modal-header{
      justify-content:center!important;
  }
  .modal-content{
      width:77%!important;
  }
  .coment{
      margin-left:89px!important;
  }
  .sub{
      justify-content:center!important;
  }
  .size{
      font-size:17px!important;
  }
  .border{
      border-right:1px solid black;
      height:100px;
  }
</style>

<div class="row">
  <div class="col-4">
    <div class="container">
      <% if @user.image.attached?%>
        <%= image_tag(@user.image, class: "profile")%>
      <%else%>
        <%= image_tag("/assets/blank.png",class:"profile")%>
      <%end%>
      <h4>User Name: <%=@user.username%></h4>

      <% if current_user.is_following?(@user) %>
        <h6><%= button_to user_unfollow_path(@user), method: :delete,remote: true do%>Unfollow</h6>
        <% end %>
      <% else %>
        <h6><%= button_to user_follow_path(@user), method: :post do%>Follow</h6>
        <% end %>
      <% end %>
      <h5> <%= link_to "", root_path, class: "btn btn-danger fa fa-angle-double-left",style:"background-color:#ff617d" %></h5>
    </div>
    <table class="col">
      <thead>
        <tr>
          <th scope="col">Posts </th>
          <th scope="col">Followers (<%= @followers.count %>)</th>
          <th scope="col">Followings (<%= @followings.count %>)</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>
            <%= @user.posts.count %></span> 
          </td>
          <td>
            <% @followers.each do |follower| %>
              <%= link_to follower.username,"/users/profile/#{follower.id}" %><br>
            <% end %>
          </td>
          <td>
            <% @followings.each do |following| %>
              <%= link_to following.username, "/users/profile/#{following.id}" %><br>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="col-8">
    <div class="row">
      <% @user.posts.each do |post|%>
        <div class="col-6">
          <%=image_tag(url_for( post.image),class:"photo") %>
          <p><%= post.bio%></p>
            <div class="like-section">
              <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= button_to '', post_like_path(post.id, pre_like), method: :delete, class: "unlike-button fa fa-thumbs-down" %>
                <%# DESTROY METHOD--LIKES CONTROLLER %>
              <% else %>
                <%= button_to '', post_likes_path(post.id), class: "like-button fa fa-thumbs-up" %>
                <%# CREATE METHOD--LIKES CONTROLLER %>
              <% end %>
              <button type="button" class="btn btn-info btn-sm dropdown" data-toggle="modal" data-target="#<%=post.id %>">
                <%= post.likes.count %> Like | <%= post.comments.count %> comments
              </button>

              <div class="modal fade" id="<%=post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <div class="close">
                        <h5 class="modal-title size" id="exampleModalLabel">Likes<br>
                        <% post.likes.each do |like| %><a class="size"><%= like.user.username %></a><br><%end%></h5>
                      </div>
                      <div class="border"></div>
                      <div class="close" style="padding-left:20px">
                        <h5 class="modal-title size" id="exampleModalLabel">Comments<br>
                        <% post.comments.each do |comment| %><a class="size"><%= comment.user.username %> --> <%= comment.body %></a><br><%end%></h5>
                      </div>
                    </div>
                    <%= form_with model: [post, post.comments.build], remote: true do |form| %>
                      <div class="modal-body">
                        <div class="form-group">
                          <label for="message-text" class="col-form-label column">Add Comment:</label><br>
                          <%= form.text_area :body ,class:"coment"%>
                        </div>
                      </div>
                      <div class="modal-footer sub">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <%= form.submit%>                
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<style>
  .profile{
      width:  191px;
      height: 183px;
      border-radius: 50%;
      box-shadow: 2px 2px 2px black;
      margin-bottom: 22px;
      border: 2px solid black;
  }
  .container{
      text-align:center;
  }
  table{
      border:1px solid black;
      text-align: center;
      width:40px;
      height:145px;
      margin-left:8px;
  }
  th{
      border:1px solid black;
      box-shadow: 1px 1px 1px black;
  }
  td{
      border: 1px solid black;
      box-shadow: 1px 1px 1px black;
  }
  .col-8{
      margin-left:454px;
      padding-right: 99px;
  }
  .photo{
      margin-top:60px;
      height: 367px;
      width: 347px;
      padding-bottom: 32px;
      border:1px solid black;
      border:10px solid transparent;
      box-shadow:2px 2px 5px black;
      margin-left:100px;
  }
  P{
      position:relative;
      bottom:26px;
      left:10px;
      margin-left:100px;
      font-family: 'Dancing Script', cursive;
  }
  .col-4{
      border-right: 1px solid black;
      position:fixed;
      font-family: 'Dancing Script', cursive;
  }
  .like-section{
      position: absolute;
      bottom: 33px;
      padding-bottom: 10px;
      right: 107px;
  }
  .like-button{
      background-color: #3897f0;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
      margin-left:30px;
      position: relative;
      top: 30px;
  }
  .like-button:hover{
      background-color: #3173c0;
  }
  .unlike-button{
      background-color: #ed4956;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
      margin-left:30px;
      position: relative;
      top: 30px;
  }
  .unlike-button:hover{
      background-color: #c81826;
  }
  .like-count{
      font-weight: bold;
      padding-left:10px;
  }
  .dropdown{
      position: absolute;
      bottom: 10px;
      left: 59px;
  }
  .row{
      width:100%;
  }
  .close{
      margin:0px!important;
      cursor: auto!important;
  }
  .column{
      margin-left:129px!important;
  }
  .modal-header{
      justify-content:center!important;
  }
  .modal-content{
      width:77%!important;
  }
  .coment{
      margin-left:89px!important;
  }
  .sub{
      justify-content:center!important;
  }
  .size{
      font-size:17px!important;
  }
  .border{
      border-right:1px solid black;
      height:100px;
  }
  h6{
      position: relative;
      top: 39px;
      left:23px;
  }
  .nav-create{
      color:black;
      padding:2px;
      font-family: 'Dancing Script', cursive;
      border:2px solid black;
      box-shadow:1px 1px 1px black;
  }
  h5{
      font-size:0.9rem;
  }
</style>

<div class="row">
  <div class="col-4">
    <div class="container">
      <% if @user.image.attached?%>
        <%= image_tag(@user.image, class: "profile")%>
      <% else%>
        <%= image_tag("/assets/blank.png",class:"profile")%>
      <%end%><hr>
      <h4>User Name: <%=current_user.username%></h4>
      <h5><%= link_to "Create Post", new_post_path, class: "nav-create" %></h5>
      <h5><%= link_to "", edit_user_path(current_user), class: "btn btn-light fa fa-edit" ,style:"background-color:#ff617d" %>        <%= link_to "", root_path, class: "btn btn-danger fa fa-angle-double-left",style:"background-color:#ff617d" %></h5>
    </div>

    <table class="col">
      <thead>
        <tr>
          <th scope="col"><h5>Posts </h5></th>
          <th scope="col"><h5>Followers (<%= @followers.count %>)</h5></th>
          <th scope="col"><h5>Followings (<%= @followings.count %>)</h5></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>
            <%= @posts.count %>
          </td>
          <td>
            <% @followers.each do |follower| %>
              <%= link_to follower.username,user_profile_path(follower.id) %><br>
            <% end %>
          </td>
          <td>
            <% @followings.each do |following| %>
              <%= link_to following.username,user_profile_path(following.id) %><br>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
 
  <div class="col-8">
    <div class="row">
      <% @user.posts.each do |post|%>
        <div class="col-6">
          <%=image_tag(url_for( post.image),class:"photo") %>
          <p><%= post.bio%></p>
            <div class="like-section">

              <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= button_to '', post_like_path(post.id, pre_like), method: :delete, class: "unlike-button fa fa-thumbs-down" %>
              <% else %>
                <%= button_to '', post_likes_path(post.id), class: "like-button fa fa-thumbs-up" %>
              <% end %>

              <button type="button" class="btn btn-info btn-sm dropdown" data-toggle="modal" data-target="#<%=post.id %>">
                <%= post.likes.count %> Like | <%= post.comments.count %> comments
              </button>
              <h6><%= button_to '', post_path(post), class: 'delete-buttons fa fa-trash-o', method: :delete ,url: user_path(current_user),remote: true %></h6>

              <div class="modal fade" id="<%=post.id %>" tabindex="-1" role="dialog" 
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <div class="close">
                        <h5 class="modal-title size" id="exampleModalLabel">Likes<br>
                          <% post.likes.each do |like| %><a class="size"><%= like.user.username %>
                          </a><br><%end%>
                        </h5>
                      </div>
                      <div class="border"></div>
                      <div class="close" style="padding-left:20px">
                        <h5 class="modal-title size" id="exampleModalLabel">Comments<br>
                        <% post.comments.each do |comment| %><a class="size"><%= comment.user.username %> --> <%= comment.body %></a><br><%end%></h5>
                      </div>
                    </div>
                    <%= form_with model: [post, post.comments.build], remote: true do |form| %>
                      <div class="modal-body">
                        <div class="form-group">
                          <label for="message-text" class="col-form-label column">Add Comment:</label><br>
                          <%= form.text_area :body ,class:"coment"%>
                        </div>
                      </div>
                      <div class="modal-footer sub">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <%= form.submit%>                
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

