config/routes.rb
# generate url and connect url and path with code

Rails.application.routes.draw do
    devise_for :users
    root "posts#index"
    get "posts/profile/:id", to: "posts#profile", as: :post_profile
    get "users/profile/:id", to: "users#profile", as: :user_profile
    get 'users', to: 'users#index'
    resources :posts do
       resources :likes, only: [:create, :destroy]
       resources :comments
    end
  
    resources :users, only: [:index,:create,:show, :edit, :update]
    resources :posts, only: [:new, :create,:update,:show,:destroy] 
    resources :users, path: '/', only: %i[show] do
      post :follow, to: 'follows#create', as: :follow
      delete :follow, to: 'follows#destroy', as: :unfollow
    end
end

















# post :follow, to: 'follows#create    '
# delete :follow, to: 'follows#destroy  '
# post :follow, to: 'follows#create', as: :follow
# delete :follow, to: 'follows#destroy', as: :unfollow
# resources :homes
# post 'follow', to: 'counts#increment', as: 'follow'
# post 'unfollow', to: 'counts#decrement', as: 'unfollow'
# root "posts"

# resources :likes, only: [:create, :destroy], shallow: true
# resources :comments, only: [:index, :create, :destroy], shallow: true
# end
# resources :posts do
#   member do
#     post 'like'
#     post 'comment'
#   end
# end
# resources :users, only: [:edit, :update]
# get '/profile', to: 'posts#profile', as: 'profile'

  # get '/messages', to: 'messages#index', as: 'messages'
  # get "/profile/:user_name" => "posts#profile",as: :profile
  # resources :posts, path: '/', param: :user_name, only: %i[show] do
  #   post :follow, to: 'posts/follows#create', as: :follow
  #   delete :follow, to: 'posts/follows#destroy', as: :unfollow
  
  # get 'search', to: 'posts#search', as: 'search_posts'
  
  
  # resources :posts do
  #   collection do
  #     get :search
  #   end
  # end





  # post "posts/p_form", to: "posts#p_form"
  # resources :users, only: [:show]

  # root to: "devise/sessions#new"

  # devise_for :models
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/post.rb
class Post < ApplicationRecord
  validate :image_presence
  has_one_attached :image

  belongs_to :user,optional: true

  has_many :likes,dependent: :destroy

  has_many :comments,dependent: :destroy

  def image_presence
    errors.add(:image,"can't be blank")unless image.attached?
  end

  
end























# def self.find_for_database_authentication(warden_conditions)
#   conditions = warden_conditions.dup
#   login = conditions.delete(:login)
#   where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
# end
# def serialised
#   {
#     id: self.id,
#     user: self.user.username,
#     image: self.image_url,
#     # likes: self.likes[0].like_count
#   }
# end



# def notify_pusher
#   Pusher.trigger('post', 'new', self.serialised)
# end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
  end
    
  def new
    @post = Post.new
  end
  
  def create
    @user = User.find(current_user.id)
    @post = @user.posts.create(post_params)
    @post.user_name = current_user.username
    if @post.save
      redirect_to root_path, notice: "Post created successfully."
    else
      render :new
    end
  end
        
  def show
    @post = Post.find(params[:id])
    @like = @post.likes.find_by(user_id: current_user.id) if current_user
    @comments = @post.comments
  end
  
  def profile
    @post = Post.find(params[:id])
    # @posts = current_user.post
    @user = @post.user_id
    @user_s = User.find(@user)
    @followers = @user_s.followers
    @followings = @user_s.followings
    
    if current_user.id == @user_s.id
      redirect_to user_path(current_user)
    end
  end
  
  def edit
    @post = Post.find(params[:id]) 
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to root_path
  end
  
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
  end

  private
  def post_params
    params.require(:post).permit(:image,:user_id,:user_name,:bio)
  end
  
end









# def sidebar
#   @posts = current_user.posts
# end
# def profile
    # @user = User.find(params[:id])
    # @posts = @user.posts
    # @followers = @user.followers
    # @followings = @user.followings
# end

# def update
#   if current_user.update(post_params)
  #     redirect_to root_path, notice: "Image uploaded successfully."
  #   else
  #     redirect_to root_path, alert: "Failed to upload image."
  #   end
  # end

  # def set_post
  #   @post = Post.find_by_username(params[:user_name])
  # end
    

#   def new
#     @post = Post.new
#     respond_to do |format|
#       format.html
#       format.js
#     end
#   end


#   def create
#     @post = Post.create(post_params)
#     redirect_to posts_path
#   end
#   def add_like
#   def add_like
#     @post = Post.find(params[:post_id])
#     if @post
#       @post.likes[0].like_count +=1

#       if @post.likes[0].save
#         respond_to do |format|
#           format.json { render :show, status: :ok }
#         end
#       end
#     end
#   end
    #     @post = Post.find(params[:post_id])
    #     if @post
    #       @post.likes[0].like_count +=1
    
    #       if @post.likes[0].save
    #         respond_to do |format|
    #           format.json { render :show, status: :ok }
    #         end
    #       end
    #     end
    #   end
    
    # def like
    #   @post = Post.find(params[:id])
    #   current_user.likes.create(post: @post)
    #   redirect_to posts_path
    # end
    
    # def comment
    #   @post = Post.find(params[:id])
    #   @comment = current_user.comments.build(comment_params)
    #   @comment.post = @post
    #   if @comment.save
    #     redirect_to posts_path
    #   else
    #     # Handle validation errors
    #   end
    # end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb

<style>
.close{
  margin:0px!important;
  cursor: auto!important;
}
.column{
  margin-left:129px!important;
}
.modal-header{
  justify-content:center!important;
}
.modal-content{
  width:77%!important;
}
.coment{
  margin-left:89px!important;
}
.sub{
  justify-content:center!important;
}
</style>

<%#debugger%>
<div class="like-section">
  <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to '', post_like_path(post.id, pre_like,format: :json), method: :delete, class: "unlike-button fa fa-thumbs-down", remote: true, onclick: "reloadLikeCount()", form: { 'id' => "post_"+ post.id.to_s , 'class' => "post_class" }%>
    <% else %>
      <%= button_to '', post_likes_path(post.id,format: :json), class: "like-button fa fa-thumbs-up", remote: true,onclick: "reloadLikeCount()", form: { 'id' => "post_"+ post.id.to_s , 'class' => "post_class" }%>
    <% end %>
</div>
<div id="ajax1">
  <button type="button" class="btn btn-dark btn-sm dropdown show" data-toggle="modal" data-target="#<%=post.id %>">
    <%= post.likes.count %> Like | <%= post.comments.count %> comments
  </button>

  <div class="modal fade" id="<%=post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="close">
            <h5 class="modal-title" id="exampleModalLabel">Likes<br>
            <% post.likes.each do |like| %>
              <a><%= like.user.username %></a><br>
            <%end%></h5>
          </div>
          <div class="close" style="padding-left:20px;border-left:1px solid black">
            <h5 class="modal-title" id="exampleModalLabel">Comments<br>
            <% post.comments.each do |comment| %><a><%= comment.user.username %> --> <%= comment.body %></a><br><%end%></h5>
          </div>
        </div>
        <%= form_with model: [post, post.comments.build], remote: true do |form| %>
          <div class="modal-body">
            <div class="form-group">
              <label for="message-text" class="col-form-label column">Add Comment:</label><br>
              <%= form.text_area :body ,class:"coment"%>
            </div>
          </div>
          <div class="modal-footer sub">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit%>                
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>





<script>


 function reloadLikeCount() {
    console.log("button", location);
    // event.preventDefault();
    // var button = event.target;
    // debugger
    location.reload();
  }

    // $(document).ready(function() {
    // $("#reload-button").on("click", function() {
    //     debugger
    //     // window.location.reload();
    //     // location.href = location.href
    //     console.log("location", location);
    //     location.assign(location.href);
    //     // alert('Reloading Page');
    // });
    // }); 
</script>

  

app/views/posts/index.html.erb
<style>
  .sidebar{
      width: 250px;
      height: 100%;
      position: fixed;
      z-index:2;
      top: 0;
      bottom:20px;
      left: 0;
      overflow-y: auto;
      background-color: #f1f1f1;
  }
  .menu-item-count{
      background-color: white;
      color: black;
      font-size: 17px;
      padding: 2px 18px;
      border-radius: 10px;
      margin-left: 5px;
  }
  h5{
      font-family: 'Dancing Script', cursive;
      font-size: 17px;
      padding-left:4px;
  }
  .vas{
      width: 797px;
      height:511px;
      border:2px solid black;
      padding-bottom:40px;
      padding-top:49px;
      margin-top:10px;
      box-shadow: 2px 2px 5px black;
  }
  h6{
      position: absolute;
      bottom: 27px;
      left: 39px;
      font-family: 'Dancing Script', cursive;
  }
  .profiles{
      width: 172px;
      height: 164px;
      border-radius: 50%;
      border: 2px solid black;
      margin-left: 24px;
      margin-top: 17px;
      box-shadow: 2px 2px 2px black;
  }
  h4{
      position: absolute;
      top: 17px;
      left: 39px;
      font-family: 'Dancing Script', cursive;
      text-shadow: 1px 1px 1px red;
  }
  .ss{
      position:relative;
  }
  .like-section{
      position: absolute;
      bottom: 18px;
      padding-bottom:10px;
      right: 182px;
  }
  .like-button{
      background-color: #3897f0;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
  }
  .like-button:hover{
      background-color: #3173c0;
  }
  .unlike-button{
      background-color: #ed4956;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
  }
  .unlike-button:hover {
      background-color: #c81826;
  }
  .dropdown{
      font-weight: bold;
      position: absolute;
      bottom: 28px;
      right: 29px;
  }
  .logo{
      width: 250px;
      height: 76px;
  } 
  .showw{
      overflow: scroll;
      height: 150px;
  }
  .profile-picture{
      border-radius: 50%;
      border: 2px solid black;
      width: 47px;
      height: 46px;
      position: relative;
      right: 35px;
      bottom: 4px;
  }
  .profiless{
      border-radius: 50%;
      border: 2px solid black;
      width: 47px;
      height: 46px;
      position: relative;
      right: 35px;
      bottom: 4px;
  }
  .user-name{
      padding-left:20px;
  }
  .nav-create{
      text-align:center;
      color:black;
      padding:2px;
      margin-left:40px;
      font-family: 'Dancing Script', cursive;
      border:2px solid black;
      box-shadow:1px 1px 1px black;
  }
  .nav-create:hover{
      background-color:#d1d1d1;
  }
  .name{
      padding-left:70px;
      color:black!important;
  }
  .roww{
      border:1px solid black;
  }
  .close{
      margin:0px!important;
      cursor: auto!important;
  }
  .column{
      margin-left:129px!important;
  }
  .modal-header{
      justify-content:center!important;
  }
  .modal-content{
      width:77%!important;
  }
  .coment{
      margin-left:89px!important;
  }
  .sub{
      justify-content:center!important;
  }
  .border{
      border-right:1px solid black;
      height:100px;
  }
</style>


<div class="container">
  <div class="row" id="post-ajax" >
    <div class="col-3">
      <div class="sidebar">
        <%=image_tag("/assets/Instaa.jpg" ,class:"logo")  %>
        <% if user_signed_in?%>
          <%if current_user.image.attached?%>
            <%= image_tag(url_for(current_user.image), class: "profiles")%><hr>
          <%else%>
            <%= image_tag("/assets/blank.png",class:"profiles") %><hr>
          <%end%>
          <h5><%=link_to current_user.username,user_path(current_user),class:"name"%></h5><br>
          <div class="row roww">
            <div class="col-3">
              <h5>Posts<br><span class="menu-item-count"><%= current_user.posts.count %></span> </h5>
            </div>
            <div class="col-4">
              <h5>Followers<br><span class="menu-item-count"><%=current_user.followers.count%></span></h5>
            </div>
            <div class="col-4">
              <h5>Followings<br><span class="menu-item-count"><%=current_user.followings.count%></span></h5>
            </div>
          </div>  
          <br><h5><%= link_to "Create Post", new_post_path, class: "nav-create" %></h5><hr>
        <% else %>
          <p>No user is currently signed in.</p>
        <% end %>
      </div>
    </div>
    <div class="col-9">
      <% @posts.each do |f|%>
        <div class="ss">
          <% if f.image.persisted?  %>
            <div><%= image_tag(url_for(f.image), class: "vas") %></div>
              <h6><%= f.bio %></h6><br>
              <% if f.user.image.persisted? %>
                <h4><%= link_to image_tag(url_for(f.user.image), class: "profile-picture"), post_profile_path(f.id) %></h4>
              <%else%>
                <h4><%= image_tag("/assets/blank.png",class:"profiless") %></h4>
              <% end %>
              <h4><%=link_to f.user_name,post_profile_path(f.id),class:"user-name"%></h4>

              <div class="like-section">
                <% pre_like = f.likes.find { |like| like.user_id == current_user.id} %>
                  <% if pre_like %>
                    <%= button_to '', post_like_path(f.id, pre_like.id), method: :delete, class: "unlike-button fa fa-thumbs-down", remote: true,data: { 'post-id' => f.id, 'url' => "/posts/" + f.id.to_s + "/likes/" + pre_like.id.to_s }%> 
                  <% else %>
                    <%= button_to '', post_likes_path(f.id), class: "like-button fa fa-thumbs-up", remote: true,method: :post,data: { 'post-id' => f.id, 'url' => "/posts/" + f.id.to_s + "/likes" }%>
                  <% end %>
              </div>
              <div class="like-count">
                <button type="button" class="btn btn-dark btn-sm dropdown show" data-toggle="modal" data-target="#<%=f.id %>">
                  <%= f.likes.count %> Like | <%= f.comments.count %> comments
                </button>

                <div class="modal fade" id="<%=f.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <div class="close">
                          <h5 class="modal-title" id="exampleModalLabel">Likes<br>
                          <% f.likes.each do |like| %>
                            <a><%= like.user.username %></a><br>
                          <%end%></h5>
                        </div>
                        <div class="border"></div>
                        <div class="close" style="padding-left:20px">
                          <h5 class="modal-title" id="exampleModalLabel">Comments<br>
                          <% f.comments.each do |comment| %><a><%= comment.user.username %> --> <%= comment.body %></a><br><%end%></h5>
                        </div>
                      </div>
                      <%= form_with model: [f, f.comments.build], remote: true do |form| %>
                        <div class="modal-body">
                          <div class="form-group">
                            <label for="message-text" class="col-form-label column">Add Comment:</label><br>
                            <%= form.text_area :body ,class:"coment"%>
                          </div>
                        </div>
                        <div class="modal-footer sub">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <%= form.submit%>                
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <%#=render "post", post:f %>
            </div>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>




<script>

$(document).ready(function() { 
  $('.like-button, .unlike-button').on('click', function() {
    // debugger
  var postId = $(this).data('post-id');
  var isUnlikeButton = $(this).hasClass('unlike-button');

  var requestType = isUnlikeButton ? 'DELETE' : 'POST';
  debugger
  var url = $(this).data('url');
  // var url = '/posts/' + postId + '/likes';
  
  $.ajax({
    type: requestType,
    url: url,
    // dataType: 'json',
    success: function(response) {
      var likeCount = response.likes_count;
      $('.like-count').text(likeCount);

      if (isUnlikeButton) {
        $('.like-button').removeClass('liked');
      } else {
        $('.like-button').addClass('liked');
      }
    },
    error: function(error) {
      console.log(error.responseText);
    }
  });
 });
});

// $('.like-button').on('click', function() {
//   var postId = $(this).data('post-id');

//   $.ajax({
//     type: 'POST',
//     url: '/posts/' + postId + '/like',
//     success: function(response) {
//       // Update the UI on successful response
//       var likeCount = response.likes_count;

//       // Update the like count display
//       $('.like-count').text(likeCount);

//       // Change the button appearance to red
//       $('.like-button').addClass('liked');
//     },
//     error: function(error) {
//       // Handle the error response
//     }
//   });
// });

</script>

 <%# $(document).ready(function() {
   // debugger
   $(document).on('ajax:complete', '#post-ajax', function(event, data, status, xhr) {
   // $('#post-ajax').on('click', function() {
     debugger
     if(data.status == 200) {
     model_form = $('#ajax1');
     model_form.html(data.responseJSON.html);
     } else {
       model_form.modal('hide');
       toastr.error('something went wrong!');
     }
   });
 });

     var projectIds = $(this).val();
     $('#ajax1').empty();
     $.ajax({
       url: '/posts/' + postIds + '/post', 
       method: 'GET',
       dataType: 'html',
       data: { postid: postIds },
       success: function(response) {
         $("#ajax1").html(response);
       }
     });
   });
 }); %>

<%# <script>
$(document).ready(function() {
  $('.like-button').on('click', function(event) {
    debugger
    // event.preventDefault();
    var button = $(this);
    var url = button.attr('href');
    var postId = button.data('post-id');
    var dropdownId = '#post-' + postId + '-dropdown';

    $.ajax({
      type: 'POST',
      url: url,
      dataType: 'json',
      success: function(response) {
        button.removeClass('like-button').addClass('unlike-button');
        button.attr('href', response.destroy_path);
        button.attr('data-confirm', 'Are you sure?');
        $(dropdownId).load(location.href + ' ' + dropdownId + ' > *');
      },
      error: function(xhr) {
        console.log(xhr.responseText);
      }
    });

  });

  $('.unlike-button').on('click', function(event) {
    // event.preventDefault();
    var button = $(this);
    var url = button.attr('href');
    var postId = button.data('post-id');
    var dropdownId = '#post-' + postId + '-dropdown';

    $.ajax({
      type: 'DELETE',
      url: url,
      dataType: 'json',
      success: function(response) {
        button.removeClass('unlike-button').addClass('like-button');
        button.attr('href', response.create_path);
        button.removeAttr('data-confirm');
        $(dropdownId).load(location.href + ' ' + dropdownId + ' > *');
      },
      error: function(xhr) {
        console.log(xhr.responseText);
      }
    });
  });
});
</script> %>

<%# <script>
  function loadDoc(){
    const xhttp= new XMLHttpRequest();
    xhttp.onload=function(){
      document.getElementById("demo").innerHTML=this.responseText;
    }
    xhttp.open("POST","_post.html.erb");
    xhttp.send();
  }
</script> %>


<%# <script>
$(document).ready(function() {
   $("#reload-button").on("click", function() {
       // window.location.reload();
       // location.href = location.href
       console.log("location");
       location.reload();
       // alert('Reloading Page');
   });
 }); 
</script> %>

app/views/posts/new.html.erb
<style>
  h1{
    padding-top:10px;
    text-align:center;
    font-family: 'Dancing Script', cursive;
  }

  .container{
    text-align:center;
    height:380px;
    width:600px;
    border:1px solid black;
    padding-top:20px;
    padding-bottom:8px;
    font-family: 'Dancing Script', cursive;
  }
</style>

<h1>Create a New Post</h1>
<div class="container">
  <%= form_with(model: @post, url: posts_path, method: :post,remote: true) do |form| %>
    <div class="form-group">

      <%= form.label :image %><br>
      <%= form.file_field :image, class: "form-control" %>

      <%= form.label :Caption %>
      <%= form.text_area :bio, class: "form-control" %><br>
    
    </div>
    <%= form.submit "Create Post", class: "btn btn-primary" %>
  <% end %><br>
  <h5> <%= link_to "", root_path, class: "btn btn-danger fa fa-angle-double-left",style:"background-color:#ff617d" %></h5>
</div>

app/views/posts/profile.html.erb
<style>
  .profile{
      width:  191px;
      height: 183px;
      border-radius: 50%;
      box-shadow: 2px 2px 2px black;
      margin-bottom: 22px;
      border: 2px solid black;
  }
  .container{
      text-align:center;
  }
  table{
      border:1px solid black;
      text-align: center;
      width:40px;
      height:145px;
      margin-left:8px;
  }
  th{
      border:1px solid black;
      box-shadow: 1px 1px 1px black;
  }
  td{
      border: 1px solid black;
      box-shadow: 1px 1px 1px black;
  }
  .col-8{
      margin-left:454px;
      padding-right: 99px;
  }
  .photo{
      margin-top:60px;
      height: 367px;
      width: 347px;
      padding-bottom: 32px;
      border:1px solid black;
      border:10px solid transparent;
      box-shadow:2px 2px 5px black;
      margin-left:100px;
  }
  P{
      position:relative;
      bottom:26px;
      left:10px;
      margin-left:100px;
      font-family: 'Dancing Script', cursive;
  }
  .col-4{
      border-right: 1px solid black;
      position:fixed;
      font-family: 'Dancing Script', cursive;
  }
  .like-section{
      position: absolute;
      bottom: 32px;
      padding-bottom:10px;
      right: 107px;
  }
  .like-button{
      background-color: #3897f0;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
      margin-left:30px;
  }
  .like-button:hover{
      background-color: #3173c0;
  }
  .unlike-button{
      background-color: #ed4956;
      height:32px;
      border: none;
      border-radius: 3px;
      color: #fff;
      cursor: pointer;
      margin-left:30px;
  }
  .unlike-button:hover{
      background-color: #c81826;
  }
  .like-count{
      font-weight: bold;
      padding-left:10px;
  }
  .dropdown{
      position: absolute;
      bottom: 10px;
      left: 59px;
  }
  .row{
      width:100%;
  }
  .close{
      margin:0px!important;
      cursor: auto!important;
  }
  .column{
      margin-left:129px!important;
  }
  .modal-header{
      justify-content:center!important;
  }
  .modal-content{
      width:77%!important;
  }
  .coment{
      margin-left:89px!important;
  }
  .sub{
      justify-content:center!important;
  }
  .size{
      font-size:17px!important;
  }
  .border{
      border-right:1px solid black;
      height:100px;
  }
</style>

<div class="row">
  <div class="col-4">
    <div class="container", id="target-container">
      <% if @user_s.image.attached?%>
        <%= image_tag(@user_s.image, class: "profile")%>
      <%else%>
        <%= image_tag("/assets/blank.png",class:"profile")%>
      <%end%>
      <h4>User Name: <%=@user_s.username%></h4>
      <% if current_user.is_following?(@user_s) %>
        <h6><%= button_to user_unfollow_path(@user_s),class:"unfollow-button", method: :delete,remote: true do%>Unfollow</h6>
        <% end %>
      <% else %>
        <h6><%= button_to user_follow_path(@user_s),class:"follow-button", method: :post,remote: true do%>Follow</h6>
        <% end %>
      <% end %>
      <h5> <%= link_to "", root_path, class: "btn btn-danger fa fa-angle-double-left",style:"background-color:#ff617d" %></h5>
    </div>
    <table class="col">
      <thead>
        <tr>
          <th scope="col">Posts </th>
          <th scope="col">Followers (<%= @followers.count %>)</th>
          <th scope="col">Followings (<%= @followings.count %>)</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>
            <%= @user_s.posts.count %></span> 
          </td>
          <td>
            <% @followers.each do |follower| %>
              <%= link_to follower.username,"/users/profile/#{follower.id}" %><br>
            <% end %>
          </td>
          <td>
            <% @followings.each do |following| %>
              <%= link_to following.username, "/users/profile/#{following.id}" %><br>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-8">
    <div class="row">
      <% @user_s.posts.each do |post|%>
        <div class="col-6">
          <%=image_tag(url_for( post.image),class:"photo") %>
            <p><%= post.bio%></p>
            <div class="like-section">
              <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '', post_like_path(post.id, pre_like), method: :delete,  class: "unlike-button fa fa-thumbs-down",remote: true, id: "reload-button", onclick: "location.reload()"%>
                <% else %>
                  <%= button_to '', post_likes_path(post.id), class: "like-button fa fa-thumbs-up",remote: true, id: "reload-button", onclick: "location.reload()"%>
                <% end %>
                <button type="button" class="btn btn-info btn-sm dropdown" data-toggle="modal" data-target="#<%=post.id %>">
                  <%= post.likes.count %> Like | <%= post.comments.count %> comments
                </button>
                <div class="modal fade" id="<%=post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <div  class="close">
                          <h5 class="modal-title size" id="exampleModalLabel">Likes<br>
                          <% post.likes.each do |like| %>
                            <a class="size"><%= like.user.username %></a><br>
                          <%end%></h5>
                        </div>
                        <div class="border"></div>
                        <div class="close" style="padding-left:20px">
                          <h5 class="modal-title size" id="exampleModalLabel">Comments<br>
                          <% post.comments.each do |comment| %><a class="size"><%= comment.user.username %> --> <%= comment.body %></a><br><%end%></h5>
                        </div>
                      </div>
                      <%= form_with model: [post, post.comments.build], remote: true do |form| %>
                        <div class="modal-body">
                          <div class="form-group">
                            <label for="message-text" class="col-form-label column">Add Comment:</label><br>
                            <%= form.text_area :body ,class:"coment"%>
                          </div>
                        </div>
                        <div class="modal-footer sub">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <%= form.submit%>                
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
