config/routes.rb
# generate url and connect url and path with code

Rails.application.routes.draw do
    devise_for :users
    root "posts#index"
    get "posts/profile/:id", to: "posts#profile", as: :post_profile
    get "users/profile/:id", to: "users#profile", as: :user_profile
    get 'users', to: 'users#index'
    resources :posts do
       resources :likes, only: [:create, :destroy]
       resources :comments
    end
  
    resources :users, only: [:index,:create,:show, :edit, :update]
    resources :posts, only: [:new, :create,:update,:show,:destroy] 
    resources :users, path: '/', only: %i[show] do
      post :follow, to: 'follows#create', as: :follow
      delete :follow, to: 'follows#destroy', as: :unfollow
    end
end

















# post :follow, to: 'follows#create    '
# delete :follow, to: 'follows#destroy  '
# post :follow, to: 'follows#create', as: :follow
# delete :follow, to: 'follows#destroy', as: :unfollow
# resources :homes
# post 'follow', to: 'counts#increment', as: 'follow'
# post 'unfollow', to: 'counts#decrement', as: 'unfollow'
# root "posts"

# resources :likes, only: [:create, :destroy], shallow: true
# resources :comments, only: [:index, :create, :destroy], shallow: true
# end
# resources :posts do
#   member do
#     post 'like'
#     post 'comment'
#   end
# end
# resources :users, only: [:edit, :update]
# get '/profile', to: 'posts#profile', as: 'profile'

  # get '/messages', to: 'messages#index', as: 'messages'
  # get "/profile/:user_name" => "posts#profile",as: :profile
  # resources :posts, path: '/', param: :user_name, only: %i[show] do
  #   post :follow, to: 'posts/follows#create', as: :follow
  #   delete :follow, to: 'posts/follows#destroy', as: :unfollow
  
  # get 'search', to: 'posts#search', as: 'search_posts'
  
  
  # resources :posts do
  #   collection do
  #     get :search
  #   end
  # end





  # post "posts/p_form", to: "posts#p_form"
  # resources :users, only: [:show]

  # root to: "devise/sessions#new"

  # devise_for :models
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1", encoding="UTF-8">
        

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js', integrity: 'sha384-...', crossorigin: 'anonymous' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/@rails/ujs@6.1.1/dist/rails-ujs.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.13.5/css/dataTables.bootstrap4.min.css' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap4.min.js' %>
    <script src="\assets\javascripts\posts.js" charset="UTF-8"></script>
    <%# <script src="\assets\javascripts\user.js" charset="UTF-8"></script> %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<style>
.navbar-expand-lg{
      width:100%;
      margin-bottom: 20px;
      z-index:1;
}
.nav-link{
      margin-left:36px;
      margin-right:5px;
      padding-bottom:10px;
      text-shadow: 2px 2px pink;
}
.nav-links{
      margin-left:36px;
      margin-right:5px;
      font-size:40px;
      color:#ff617d;
   /* transform: rotate(20deg); */
}

.navbar-light .navbar-nav .nav-link{
      color: rgb(16 15 15);
}
  
.navbar-light .navbar-nav .nav-link:hover{
      color: black;
      border:1px solid white;
      background-color:white;
      border-radius:30px;
}

</style>
</head>

<body>

<nav class="navbar-expand-lg sticky-top  navbar-light bg-light">
  <div class="con"style="background-color: #f1f1f1;">
    <a class="navbar-brand" href="#"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
             <%= link_to "home", root_path, class: "nav-link fa fa-home",style:"font-size:20px" %>  
             <%# ROOT PATH %>    <%#  INDEX METHOD--POST CONTROLLER %>
        </li>
        <li class="nav-item">
             <%= link_to "user", users_path ,class: "nav-link fa fa-users",style:"font-size:20px" %>  
        </li>
             <%# USER///INDEX.HTML.ERB %>     <%# INDEX METHOD--USER CONTROLLER%>
        <%# <li class="nav-item"> %>
             <%#= link_to "Create", new_post_path, class: "nav-link fa fa-paperclip",style:"font-size:20px" %> 
             <%# POST///NEW.HTML.ERB %>     <%#  NEW  METHOD--POST CONTROLLER %>
        <%# </li> %>
        <li class="nav-item">
             <%= link_to "profile", user_path(current_user) ,class: "nav-link fa fa-user",style:"font-size:20px" %>  
        </li>
             <%# USER///SHOW.HTML.ERB %>     <%# SHOW METHOD--USER CONTROLLER%>
        <li class="nav-item">
             <%= button_to "logout", destroy_user_session_path, method: :delete, class: "nav-link btn btn-link fa fa-sign-out",style:"font-size:20px" %> 
             <%# DEVISE///SESSION///SIGN_OUT.HTML.ERB %>   <%# DESTROY METHOD--DEVISE--SESSION CONTROLLER%>
        </li>
        <li class="nav-item">
             <span class= "nav-links fa fa-instagram"></span>
        </li>
      </ul>
    </div>
  </div>
</nav>
       <%= yield  %>

</body>
</html>

app/views/layouts/my_devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1", encoding="UTF-8">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 </head>

  <body>
       <%= yield  %>

  </body>
</html>